name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ECommerce.sln
    - name: Build
      run: dotnet build ECommerce.sln --no-restore
    - name: Test
      run: dotnet test ECommerce.sln --no-build --verbosity normal
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file docker-compose.yml --tag my-image-name:$(date +%s)